-- MySQL Script generated by MySQL Workbench
-- Sun Mar 26 19:19:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`COMPROMISSOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COMPROMISSOS` (
  `ID` INT NOT NULL,
  `DATA` DATE NULL,
  `CATEGORIA` VARCHAR(45) NULL,
  `ALARME` TIME NULL,
  `NOTA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ANOTACOES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ANOTACOES` (
  `ID` INT NOT NULL,
  `DATA` DATE NULL,
  `NOTA` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HABITOS_DIARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HABITOS_DIARIOS` (
  `ID` INT NOT NULL,
  `HABITO` VARCHAR(45) NULL,
  `CHECKLIST` BINARY(1) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOGINS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LOGINS` (
  `ID` INT NOT NULL,
  `LOGIN` VARCHAR(45) NULL,
  `SENHA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CALENDÁRIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CALENDÁRIO` (
  `ID` INT NOT NULL,
  `DATA` DATE NULL,
  `ANOTACOES_ID` INT NOT NULL,
  `COMPROMISSOS_ID` INT NOT NULL,
  `HABITOS_DIARIOS_ID` INT NOT NULL,
  `LOGINS_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_CALENDÁRIO_ANOTACOES1_idx` (`ANOTACOES_ID` ASC) VISIBLE,
  INDEX `fk_CALENDÁRIO_COMPROMISSOS1_idx` (`COMPROMISSOS_ID` ASC) VISIBLE,
  INDEX `fk_CALENDÁRIO_HABITOS_DIARIOS1_idx` (`HABITOS_DIARIOS_ID` ASC) VISIBLE,
  INDEX `fk_CALENDÁRIO_LOGINS1_idx` (`LOGINS_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CALENDÁRIO_ANOTACOES1`
    FOREIGN KEY (`ANOTACOES_ID`)
    REFERENCES `mydb`.`ANOTACOES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CALENDÁRIO_COMPROMISSOS1`
    FOREIGN KEY (`COMPROMISSOS_ID`)
    REFERENCES `mydb`.`COMPROMISSOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CALENDÁRIO_HABITOS_DIARIOS1`
    FOREIGN KEY (`HABITOS_DIARIOS_ID`)
    REFERENCES `mydb`.`HABITOS_DIARIOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CALENDÁRIO_LOGINS1`
    FOREIGN KEY (`LOGINS_ID`)
    REFERENCES `mydb`.`LOGINS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
